-- V1__Create_Tenant_And_User_Tables.sql
-- Tipologia: DDL (Data Definition Language) para Oracle SQL

-- 1. Criação da Tabela de Tenants (Corporações Clientes)
CREATE TABLE tb_tenant (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR2(36) NOT NULL UNIQUE, -- UUID para exposição pública (Segurança OWASP)
    company_name VARCHAR2(100) NOT NULL,
    cnpj VARCHAR2(14) NOT NULL UNIQUE,
    subscription_plan VARCHAR2(20) DEFAULT 'STANDARD' NOT NULL, -- Valores: STANDARD, ENTERPRISE
    is_active NUMBER(1, 0) DEFAULT 1 NOT NULL, -- 1 = Ativo, 0 = Inativo (Soft Delete)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Índice para acelerar a busca de corporações no roteamento de APIs
CREATE INDEX idx_tenant_cnpj ON tb_tenant(cnpj);

-- 2. Criação da Tabela de Usuários (Colaboradores, RH, C-Level)
CREATE TABLE tb_user (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id NUMBER NOT NULL,
    external_id VARCHAR2(36) NOT NULL UNIQUE, -- UUID para identificação em chamadas ao Kafka/IA
    full_name VARCHAR2(150) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL, -- Senhas SEMPRE hasheadas (Bcrypt/Argon2)
    role_type VARCHAR2(20) NOT NULL, -- Valores: ADMIN_RH, C_LEVEL, EMPLOYEE
    is_active NUMBER(1, 0) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- Trava de Integridade Relacional (Isolamento Multi-Tenant)
    CONSTRAINT fk_user_tenant FOREIGN KEY (tenant_id) REFERENCES tb_tenant(id)
);

-- Índices para performance nas regras de negócio e dashboards
CREATE INDEX idx_user_tenant ON tb_user(tenant_id);
CREATE INDEX idx_user_email ON tb_user(email);