-- V3: Tabela de auditoria transacional para resgate de pontos (Vouchers/Marketplace)

CREATE TABLE tb_reward_redemption (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    user_external_id VARCHAR2(255 CHAR) NOT NULL,
    reward_type VARCHAR2(100 CHAR) NOT NULL,
    coins_deducted NUMBER(19, 2) NOT NULL,
    processed_at TIMESTAMP NOT NULL
);
