-- V5__Frontend_Gamification_Alignment.sql
-- Alinhando o schema do banco de dados com as necessidades do Frontend e os novos recursos sociais.

-- 1. Criação de Departamentos para Ranking de Equipes
CREATE TABLE tb_department (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_dept_tenant FOREIGN KEY (tenant_id) REFERENCES tb_tenant(id)
);

-- 2. Atualizações na Tabela de Empresa (Tenant)
-- Adiciona cache/saldo de carbono global da empresa para exibição no Dashboard Gerencial
ALTER TABLE tb_tenant ADD total_carbon_saved NUMBER(19, 4) DEFAULT 0.0 NOT NULL;

-- 3. Atualizações na Tabela de Usuário (Gamificação)
ALTER TABLE tb_user ADD department_id NUMBER;
ALTER TABLE tb_user ADD streak_days NUMBER(10, 0) DEFAULT 0 NOT NULL;
ALTER TABLE tb_user ADD user_level NUMBER(10, 0) DEFAULT 1 NOT NULL;
ALTER TABLE tb_user ADD CONSTRAINT fk_user_department FOREIGN KEY (department_id) REFERENCES tb_department(id);

-- 4. Quadro de Medalhas (Badges)
CREATE TABLE tb_badge (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(255),
    icon_url VARCHAR2(255)
);

CREATE TABLE tb_user_badge (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    badge_id NUMBER NOT NULL,
    awarded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_userbadge_user FOREIGN KEY (user_id) REFERENCES tb_user(id),
    CONSTRAINT fk_userbadge_badge FOREIGN KEY (badge_id) REFERENCES tb_badge(id)
);

-- 5. Catálogo do Marketplace (Rewards)
CREATE TABLE tb_reward (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id NUMBER NOT NULL,
    title VARCHAR2(100) NOT NULL,
    cost_points NUMBER(19, 2) NOT NULL,
    is_active NUMBER(1, 0) DEFAULT 1 NOT NULL,
    CONSTRAINT fk_reward_tenant FOREIGN KEY (tenant_id) REFERENCES tb_tenant(id)
);

-- 6. Objetivo Ativo do Usuário
CREATE TABLE tb_user_goal (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL UNIQUE, -- 1 objetivo ativo por vez
    reward_id NUMBER NOT NULL,
    target_points NUMBER(19, 2) NOT NULL,
    current_points NUMBER(19, 2) DEFAULT 0.0 NOT NULL,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_usergoal_user FOREIGN KEY (user_id) REFERENCES tb_user(id),
    CONSTRAINT fk_usergoal_reward FOREIGN KEY (reward_id) REFERENCES tb_reward(id)
);
