services:
  # Core Transacional Relacional
  oracle-db:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: ecotrack-oracle
    environment:
      - ORACLE_PASSWORD=secret_local_pass
      - APP_USER=ecotrack_admin
      - APP_USER_PASSWORD=secret_local_pass
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Mensageria Assíncrona (Eventos de Sustentabilidade) - Versão Fixada
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093,CONTROLLER://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - kafka_data:/bitnami/kafka

  # Event Sourcing para Trilhas de Auditoria (Escopo 3)
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: ecotrack-dynamo
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  # Inteligência Artificial e Orquestração LangGraph
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: ecotrack-ai-worker
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY:-}
      - LANGCHAIN_PROJECT=ecotrack-ai
      - OLLAMA_BASE_URL=http://host.docker.internal:11434

volumes:
  oracle_data:
  kafka_data: