# Arquivo: src/main/resources/application.yml
spring:
  application:
    name: ecotrack-core

  # Configuração de Profiles (Ativando o ambiente de desenvolvimento por padrão localmente)
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Configuração Segura de Banco de Dados (Oracle SQL)
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
    username: ${DB_USER:ecotrack_admin}
    password: ${DB_PASSWORD:secret_local_pass} # Injetado via variável de ambiente no CI/CD
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 20000 # 20 segundos máximo para tentar conexão
      maximum-pool-size: 15     # Evita exaustão de recursos no DB
      minimum-idle: 5

  # Configuração ORM (Hibernate)
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate # Bloqueia alterações automáticas no schema para garantir integridade
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

  # Configuração de Mensageria (Apache Kafka)
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3 # Tenta reenviar a mensagem em caso de falha transitória do broker
    consumer:
      group-id: ecotrack-core-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

# Configuração de Tolerância a Falhas (Anti-Loop / Circuit Breaker)
resilience4j.circuitbreaker:
  instances:
    aiValidationService:
      registerHealthIndicator: true
      slidingWindowSize: 10 # Avalia as últimas 10 chamadas
      failureRateThreshold: 50 # Abre o circuito se 50% falharem
      waitDurationInOpenState: 10000 # Espera 10s antes de tentar novamente (Half-Open)
      permittedNumberOfCallsInHalfOpenState: 3

resilience4j.timelimiter:
  instances:
    aiValidationService:
      timeoutDuration: 5s # Interrompe chamadas à IA que demorem mais de 5 segundos

# Observabilidade para QA e DevOps
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always